### ISSUE TITLE
License

### ISSUE THREAD

**Issue by emartynov** [adobe/aepsdk-userprofile-android#19]
Hi people,

This repository says that the library is distributed with Apache 2.0 license. However, if you open [pom file](https://repo1.maven.org/maven2/com/adobe/marketing/mobile/userprofile/2.0.0/userprofile-2.0.0.pom) then you will see Adobe proprietary license.

The iOS version of the library has the correct license.

**Comment by yangyansong-adbe** [comment]
It's a duplicated issue of https://github.com/adobe/aepsdk-core-android/issues/415, close it.

**Comment by emartynov** [comment]
I don't think it is duplicate since this library pom has a different license from Apache in documentation
