### ISSUE TITLE
Wrong license in the published pom. 

### ISSUE THREAD

**Issue by yogurtearl** [adobe/aepsdk-userprofile-android#23]
### Expected Behaviour

License in the published pom.xml should match the `LICENSE` file on the repo, which is Apache 2.0. 

### Actual Behaviour

The published license info does not match the  LICENSE file in this repo:
https://github.com/adobe/aepsdk-userprofile-android/blob/bc6f9064bf62766e87b05a60bc3f1e22aebc21f9/code/userprofile/release.gradle#L57-L59

See published pom here:
https://central.sonatype.com/artifact/com.adobe.marketing.mobile/userprofile/2.0.0

Instead it should be:

https://github.com/adobe/aepsdk-core-android/blob/d7ca19d10efb8ad749f62511840c033c0ff7623c/code/core/release.gradle#L33-L37
```groovy
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        distribution = 'repo'
                    }
```

**Comment by yangyansong-adbe** [comment]
@yogurtearl  We appreciate you bringing this to our attention! We have noticed this issue and decided to resolve it in the next release. Are you unable to use the `userprofile` library due to this issue? Please inform me if this blocks you and we can prioritize the release date accordingly.

**Comment by yogurtearl** [comment]
This was blocking us, but your acknowledgement here that a fix is coming helps serve as documentation for the necessary approvals for a short team work around. 

Next release is fine for us.

**Comment by yangyansong-adbe** [comment]
I will close this issue because the open-source license was corrected in the new [artifact](https://central.sonatype.com/artifact/com.adobe.marketing.mobile/userprofile/2.0.1/overview). @yogurtearl please feel free to reopen the issue if you have other questions about the license info.
